# Generated by Django 5.2.4 on 2026-04-19 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('due_day', models.PositiveSmallIntegerField(default=5)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('late_fee_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('percentage', 'Percentage')], default='none', max_length=20)),
                ('late_fee_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('lease_document', models.FileField(blank=True, upload_to='lease_documents/')),
                ('notes', models.TextField(blank=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_145517_idx'), models.Index(fields=['property', 'start_date', 'end_date'], name='leases_leas_propert_c3ed87_idx'), models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9c2189_idx')],
            },
        ),
    ]
