# Generated by Django 5.2.15 on 2026-06-08 14:11

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0002_alter_property_rent_default_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='late_fee_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('rent_amount__gte', 0)), name='leases_rent_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('security_deposit__gte', 0)), name='leases_security_deposit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('late_fee_value__gte', 0)), name='leases_late_fee_value_non_negative'),
        ),
    ]
