# Generated by Django 5.2.15 on 2026-06-08 14:11

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_lease_late_fee_value_alter_lease_rent_amount_and_more'),
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseinstallment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='leaseinstallment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='leaseinstallment',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='leaseinstallment',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='leaseinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='payments_installment_amount_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leaseinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('late_fee_amount__gte', 0)), name='payments_installment_late_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leaseinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='payments_installment_amount_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leaseinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_amount__gte', 0)), name='payments_installment_outstanding_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payments_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='payments_allocation_amount_non_negative'),
        ),
    ]
